In [1]:
import numpy as np

In [3]:
arr = np.array((1,2,4,5,6))

print(arr)
type(arr)

[1 2 4 5 6]


numpy.ndarray

# dimention of array

In [5]:
# 0 dimensional array

arr0 = np.array(6)
print(arr0)
print(type(arr0))
print(arr0.ndim)

6
<class 'numpy.ndarray'>
0


In [14]:
# one-dimensional array

arr1 =np.array((4,6,3,2,3))
print(arr1)
print(type(arr1))
print(arr1.ndim)

# accesing 1d array

print(arr1[1])

# Slicing the array
arr_slice = arr1[1:4]

print(arr_slice)

[4 6 3 2 3]
<class 'numpy.ndarray'>
1
6
[6 3 2]


In [21]:
# 2-dimensional array

arr2= np.array(((23,4,53,64),(5,63,53,2)))
print(arr2)
print(type(arr2))
print(arr2.ndim)

#accessing 2d array

print(arr2[0,0])
print(arr2[1,0])

# slicing 2d array

nw_arr2 = arr2[0,1:3]
print(nw_arr2)

[[23  4 53 64]
 [ 5 63 53  2]]
<class 'numpy.ndarray'>
2
23
5
[ 4 53]


In [10]:
# 3 and more dimensional array

arr3 = np.array([[[3,5]],[[6,5]],[[7,8]]])

print(arr3)
print(type(arr3))
print(arr3.ndim)

[[[3 5]]

 [[6 5]]

 [[7 8]]]
<class 'numpy.ndarray'>
3


In [7]:
# array containing only zero... and the number is a floating point type

zero_arr = np.zeros(3)
print(zero_arr)

# 2d array of zeros

zero2_arr = np.zeros([3,3])
print(zero2_arr)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# array containing only 1...and here one is a floating point number

one_arr =np.ones(5)
print(one_arr)

#2d array

one_arr = np.ones([4,4])
print(one_arr)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:

# Checking the data type inside an array

arr_data_check = np.array([5,4,7,4,3,5])

print(arr_data_check.dtype)

int64


In [14]:
# Creating a specific data type array

st_arr = np.array([2,3,5,4,3], dtype = 'S')

print(st_arr.dtype)

st_arr2 = np.array([3,4,6,2], dtype= 'i')
print(st_arr2.dtype)

int_arr = np.array([2,3,4,5,6], dtype= 'i2')
print(int_arr.dtype)

|S1
int32
int16


# shape of an array

In [19]:
# The shape of an array is the number of elements in each direction

arr_shape = np.array([3,7,8,9,2])
print(arr_shape.shape)

arr2_shape = np.array([[2,3,6,7],[6,8,9,6]])
print(arr2_shape.shape)

arr3_shape = np.array([[[2,3,6,7],[6,8,9,6],[4,9,8,4]]])
print(arr3_shape.shape)

(5,)
(2, 4)
(1, 3, 4)


# joining array

In [21]:

# Joining two or more arrays into one

ar1 = np.array([10,32,67,35])
ar2 =np.array([45,21,38,34])

ar3 = np.concatenate((ar1,ar2))
print(ar3)



[10 32 67 35 45 21 38 34]
[ 55  53 105  69]


In [22]:
# Joining 2-dimensional array

arr_2d_1 = np.array([[1,2],[6,4]])
arr_2d_2 = np.array([[3,7],[8,9]])

# we join the array along the axis 

con_arr = np.concatenate((arr_2d_1, arr_2d_2), axis=1) # 1 represent along x axis
print(con_arr)

con_arr2 = np.concatenate((arr_2d_1, arr_2d_2), axis=0) #0 represent along y axis
print(con_arr2)

[[1 2 3 7]
 [6 4 8 9]]
[[1 2]
 [6 4]
 [3 7]
 [8 9]]


# spliting an array

In [24]:
full_arr = np.array([1,2,3,4,5,6])
split_array= np.array_split(full_arr,4)
print(split_array)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel and flatten

In [27]:
# It converts a multidimensional array to a one-dimensional array
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)
print("the previous dimension is :",arr_3d.ndim)

arr_1d = arr_3d.ravel()

print(arr_1d)
print("Now the new dimension is :",arr_1d.ndim)

# flatten() function also does the same job

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
the previous dimension is : 3
[1 2 3 4 5 6 7 8 9]
Now the new dimension is : 1


# unique values function

In [29]:
val = np.array([2,4,6,7,5,4,2,7,8,9,7,4,2,4,7])

unique_val = np.unique(val)
print(unique_val)

[2 4 5 6 7 8 9]
